// populateObjectInfo.js
import admin from 'firebase-admin';
import fs from 'fs';

// Load service account JSON
const serviceAccount = JSON.parse(
  fs.readFileSync('./green-lens-47e9b-firebase-adminsdk-fbsvc-9af6311d8b.json', 'utf8')
);

// Initialize Admin SDK
admin.initializeApp({
  credential: admin.credential.cert(serviceAccount),
});

const db = admin.firestore();

// 🌸 Flowers
const flowerData = [
  {
    id: "blackberry lily",
    name: "Blackberry Lily",
    description: "A vibrant flower with orange petals and red spots, known for its unique seed pods resembling blackberries.",
    characteristics: "Dotted orange petals, sturdy stems, and black seed clusters.",
    healthTip: "Grows best in full sun with moderate watering. Yellowing leaves may indicate overwatering.",
    funFact: "Traditionally used in herbal medicine for sore throats.",
  },
  {
    id: "buttercup",
    name: "Buttercup",
    description: "A small, bright yellow flower commonly found in meadows and gardens.",
    characteristics: "Glossy petals, short stems, thrives in cool climates.",
    healthTip: "Healthy buttercups have shiny petals; drooping ones often signal waterlogging.",
    funFact: "Buttercups are mildly toxic but famous for their glossy petal shine used in optical studies.",
  },
  {
    id: "canna lily",
    name: "Canna Lily",
    description: "A tropical flower with large colorful blooms and broad green or purple leaves.",
    characteristics: "Fast-growing, moisture-loving, blooms in summer.",
    healthTip: "Requires regular sunlight and moist soil; pale leaves may suggest nutrient deficiency.",
    funFact: "Canna roots are edible when cooked and are used in some Asian cuisines.",
  },
  {
    id: "foxglove",
    name: "Foxglove",
    description: "A tall flowering plant with bell-shaped blossoms that range from purple to white.",
    characteristics: "Towering stalks, tubular flowers, attractive to bees.",
    healthTip: "Healthy foxgloves stand upright; wilting indicates heat stress or root rot.",
    funFact: "Contains compounds used in heart medicine — handle with care as it's toxic when raw.",
  },
  {
    id: "hibiscus",
    name: "Hibiscus",
    description: "A tropical shrub producing large, colorful flowers that attract pollinators.",
    characteristics: "Five broad petals, long stamens, thrives in humid climates.",
    healthTip: "Healthy hibiscus has firm green leaves and frequent blooms; leaf yellowing can indicate nutrient loss.",
    funFact: "Used for hibiscus tea and skincare; rich in antioxidants and vitamin C.",
  },
  {
    id: "marigold",
    name: "Marigold",
    description: "A hardy, bright orange or yellow flower used in festivals and companion planting.",
    characteristics: "Strong scent, pest-repellent, fast-growing annual.",
    healthTip: "Blooms fade early when overwatered; prune old flowers to encourage new growth.",
    funFact: "Petals are edible and used in salads and as a natural dye.",
  },
  {
    id: "mexican aster",
    name: "Mexican Aster",
    description: "Also known as cosmos, these flowers have daisy-like petals in pink, white, and purple.",
    characteristics: "Light stems, delicate petals, grows in poor soil.",
    healthTip: "Tall and vibrant stems mean good sunlight; drooping signals excessive watering.",
    funFact: "Attracts bees and butterflies, making it a pollinator's favorite.",
  },
  {
    id: "morning glory",
    name: "Morning Glory",
    description: "A climbing vine producing trumpet-shaped flowers that bloom in the morning.",
    characteristics: "Fast-growing, heart-shaped leaves, blooms early.",
    healthTip: "Healthy vines climb rapidly; yellowing indicates root-bound or dry soil.",
    funFact: "Flowers bloom in the morning and close by noon — a natural clock for gardeners.",
  },
  {
    id: "rose",
    name: "Rose",
    description: "A classic flowering shrub renowned for its beautiful, fragrant flowers and thorny stems.",
    characteristics: "Fragrant layered petals, thorny stems, various colors, symbolic meaning",
    healthTip: "New buds and green stems indicate good health; black spots often mean fungal infection.",
    funFact: "Rose petals are edible and often used in desserts and perfumes.",
  },
  {
    id: "sunflower",
    name: "Sunflower",
    description: "A tall, bright yellow flower that follows the sun across the sky.",
    characteristics: "Large circular blooms, edible seeds, and thick stalks.",
    healthTip: "Healthy sunflowers stand tall and follow sunlight; drooping heads may suggest dehydration.",
    funFact: "Sunflowers turn to face the sun — a behavior called heliotropism.",
  },
  {
    id: "fire lily",
    name: "Fire Lily",
    description: "Bright orange-red flowers with fiery tones.",
    characteristics: "Tall stems, trumpet-shaped flowers, thrives in tropical climates",
    healthTip: "Healthy Fire Lilies have firm, upright stems and vibrant blooms; drooping flowers or yellowing leaves may indicate insufficient sunlight or overwatering.",
    funFact: "Also known as Crinum Lily, often used in landscaping.",
  },
  {
    id: "canterbury bells",
    name: "Canterbury Bells",
    description: "Bell-shaped blooms in pastel shades.",
    characteristics: "Biennial, prefers cool summers, upright stems",
    healthTip: "Check for upright stems and strong blooms; wilting or browning flowers suggest inconsistent watering or excessive heat.",
    funFact: "Traditionally used in cottage gardens.",
  },
  {
    id: "bolero deep blue",
    name: "Bolero Deep Blue",
    description: "Vivid deep blue flowers forming dense clusters.",
    characteristics: "Compact, hardy, blooms in summer",
    healthTip: "Healthy plants display full, vibrant flower clusters; sparse flowering or pale colors may indicate nutrient deficiency or insufficient sunlight.",
    funFact: "Popular in ornamental beds for color contrast.",
  },
  {
    id: "pink primrose",
    name: "Pink Primrose",
    description: "Delicate pink flowers with bright yellow centers.",
    characteristics: "Low-growing, thrives in partial shade",
    healthTip: "Leaves should be bright green and flowers vivid; wilting or brown edges indicate underwatering or poor soil drainage.",
    funFact: "Symbolizes youth and renewal in flower language.",
  },
  {
    id: "prince of wales feathers",
    name: "Prince of Wales Feathers",
    description: "Unique foliage resembling feathers with subtle flowers.",
    characteristics: "Climbing plant, ornamental foliage",
    healthTip: "Leaves should remain firm and richly colored; limp growth or pale leaves may signal insufficient support or irregular watering.",
    funFact: "Named for its feathery leaf pattern.",
  },
  {
    id: "moon orchid",
    name: "Moon Orchid",
    description: "Elegant white orchids with yellow centers.",
    characteristics: "Epiphytic, thrives in humid environments",
    healthTip: "Check for firm roots and upright blooms; drooping or spotted flowers suggest overwatering, low humidity, or insufficient light.",
    funFact: "Popular as a decorative orchid in homes.",
  },
  {
    id: "globe flower",
    name: "Globe Flower",
    description: "Spherical yellow flowers on tall stems.",
    characteristics: "Moisture-loving, attracts pollinators",
    healthTip: "Tall, straight stems and bright yellow blooms indicate healthy growth; drooping flowers or pale petals may indicate inadequate water or sunlight.",
    funFact: "Commonly found in alpine meadows.",
  },
  {
    id: "grape hyacinth",
    name: "Grape Hyacinth",
    description: "Small, bell-shaped blue flowers resembling grapes.",
    characteristics: "Bulbous perennial, blooms in spring",
    healthTip: "Healthy Grape Hyacinths have firm, upright flower spikes; drooping or discolored blooms may indicate poor soil drainage or insufficient sunlight.",
    funFact: "Often used in spring borders for color.",
  },
  {
    id: "corn poppy",
    name: "Corn Poppy",
    description: "Bright red flowers with black centers.",
    characteristics: "Annual, grows quickly in fields",
    healthTip: "Bright, fully open petals and upright stems indicate healthy growth; wilting or faded flowers suggest heat stress or drought.",
    funFact: "Symbol of remembrance in many countries.",
  },
  {
    id: "toad lily",
    name: "Toad Lily",
    description: "Spotted, orchid-like flowers in fall.",
    characteristics: "Shade-loving, blooms in late season",
    healthTip: "Check that stems are sturdy and leaves green; limp flowers or yellowing leaves indicate too much sun or inconsistent watering.",
    funFact: "Named for its unusual spotted flowers.",
  },
  {
    id: "siam tulip",
    name: "Siam Tulip",
    description: "Tropical pink and purple cone-shaped flowers.",
    characteristics: "Perennial, grows in tropical conditions",
    healthTip: "Healthy Siam Tulips have upright stems and vibrant blooms; drooping flowers may indicate low humidity or insufficient watering.",
    funFact: "Native to Thailand; also called Curcuma.",
  },
  {
    id: "red ginger",
    name: "Red Ginger",
    description: "Vibrant red flower spikes with lush green foliage.",
    characteristics: "Tropical, grows in partial shade",
    healthTip: "Look for firm, unblemished leaves and bright flower spikes; pale leaves or drooping blooms suggest inadequate moisture or light.",
    funFact: "Used in tropical floral arrangements.",
  },
  {
    id: "spring crocus",
    name: "Spring Crocus",
    description: "Early blooming small purple or white flowers.",
    characteristics: "Bulbous, emerges in late winter to spring",
    healthTip: "Healthy crocuses have upright flowers and vibrant petals; drooping or fading flowers suggest poor soil or lack of sunlight.",
    funFact: "Symbolizes new beginnings in spring.",
  },
  {
    id: "alpine sea holly",
    name: "Alpine Sea Holly",
    description: "Spiky blue flowers with silvery foliage.",
    characteristics: "Drought-tolerant, attracts pollinators",
    healthTip: "Check that leaves are silvery-blue and firm; brown or limp foliage may indicate overwatering or fungal issues.",
    funFact: "Used in rock gardens for texture.",
  },
  {
    id: "garden phlox",
    name: "Garden Phlox",
    description: "Clusters of colorful flowers with sweet fragrance.",
    characteristics: "Perennial, upright growth",
    healthTip: "Healthy phlox displays upright stems and vibrant blooms; wilting or faded flowers indicate drought stress or fungal disease.",
    funFact: "Attracts butterflies and hummingbirds.",
  },
  {
    id: "globe thistle",
    name: "Globe Thistle",
    description: "Round, spiky blue flowers on tall stems.",
    characteristics: "Drought-tolerant perennial",
    healthTip: "Firm, spiky blooms indicate healthy plants; drooping or discolored flowers suggest lack of sun or water.",
    funFact: "Popular in dried flower arrangements.",
  },
  {
    id: "tiger lily",
    name: "Tiger Lily",
    description: "Orange, spotted, trumpet-shaped flowers.",
    characteristics: "Perennial, grows from bulbs",
    healthTip: "Check for upright, vibrant blooms; drooping or pale flowers indicate poor soil, drought, or disease.",
    funFact: "Named for its tiger-like spots.",
  },
  {
    id: "ball moss",
    name: "Ball Moss",
    description: "Small spherical mosses growing on tree branches.",
    characteristics: "Non-parasitic epiphyte, thrives in humidity",
    healthTip: "Healthy Ball Moss is green and firm; gray or brittle growth may indicate too little humidity or poor air circulation.",
    funFact: "Often found in Southern US trees.",
  },
  {
    id: "love in the mist",
    name: "Love In The Mist",
    description: "Delicate flowers surrounded by feathery foliage.",
    characteristics: "Annual, grows in sun or partial shade",
    healthTip: "Check that flowers are fully open and foliage is green; wilting or discolored leaves indicate drought or excess water.",
    funFact: "Produces decorative seed pods.",
  },
  {
    id: "monkshood",
    name: "Monkshood",
    description: "Blue hooded flowers, tall spikes.",
    characteristics: "Perennial, poisonous if ingested",
    healthTip: "Healthy plants have firm stems and vibrant blooms; yellowing leaves suggest overwatering or poor soil.",
    funFact: "Also called Aconitum; used in traditional medicine.",
  },
  {
    id: "blanket flower",
    name: "Blanket Flower",
    description: "Red and yellow daisy-like flowers.",
    characteristics: "Drought-tolerant perennial",
    healthTip: "Upright stems and bright flowers indicate good health; faded blooms suggest lack of sunlight or insufficient water.",
    funFact: "Popular in pollinator gardens.",
  },
  {
    id: "king protea",
    name: "King Protea",
    description: "Large, dramatic flowers with central dome.",
    characteristics: "Evergreen shrub, slow-growing",
    healthTip: "Firm, symmetrical flowers and healthy leaves indicate proper growth; drooping or discolored flowers suggest nutrient deficiency.",
    funFact: "National flower of South Africa.",
  },
  {
    id: "oxeye daisy",
    name: "Oxeye Daisy",
    description: "White petals with yellow centers.",
    characteristics: "Perennial, spreads easily",
    healthTip: "Vibrant, upright flowers indicate healthy plants; floppy stems or yellow leaves may indicate drought or nutrient deficiency.",
    funFact: "Common in wildflower meadows.",
  },
  {
    id: "yellow iris",
    name: "Yellow Iris",
    description: "Tall perennials with bright yellow flowers.",
    characteristics: "Moisture-loving, prefers full sun",
    healthTip: "Firm stalks and vibrant petals indicate healthy plants; wilting flowers suggest dry soil or insufficient sunlight.",
    funFact: "Often grows near ponds and wetlands.",
  },
  {
    id: "cautleya spicata",
    name: "Cautleya Spicata",
    description: "Exotic yellow-orange flowers on tall spikes.",
    characteristics: "Tropical perennial, prefers shade and moist soil",
    healthTip: "Healthy spikes are upright with vibrant flowers; drooping or faded blooms suggest low humidity or improper watering.",
    funFact: "Related to the ginger family, native to Asia.",
  },
  {
    id: "carnation",
    name: "Carnation",
    description: "Fragrant flowers in pink, red, white, and striped varieties.",
    characteristics: "Perennial, bushy growth",
    healthTip: "Firm stems and bright flowers indicate health; wilting or discolored petals suggest poor light or water issues.",
    funFact: "Often used in bouquets and corsages.",
  },
  {
    id: "silverbush",
    name: "Silverbush",
    description: "Silver-grey foliage with small colorful flowers.",
    characteristics: "Drought-tolerant, prefers full sun",
    healthTip: "Healthy Silverbush shows firm leaves and vibrant flowers; brown or limp leaves indicate overwatering or disease.",
    funFact: "Used as an ornamental plant in gardens.",
  },
  {
    id: "bearded iris",
    name: "Bearded Iris",
    description: "Tall irises with intricate, ruffled petals.",
    characteristics: "Perennial, prefers sunny locations",
    healthTip: "Firm rhizomes and vibrant flowers indicate health; soft or rotting rhizomes suggest overwatering.",
    funFact: "The 'beard' refers to fuzzy hairs on the petals.",
  },
  {
    id: "black eyed susan",
    name: "Black-Eyed Susan",
    description: "Bright yellow petals with a dark brown center.",
    characteristics: "Annual or perennial, drought-tolerant",
    healthTip: "Upright stems and vivid petals show healthy growth; drooping heads may indicate dehydration.",
    funFact: "Symbol of encouragement and motivation.",
  },
  {
    id: "windflower",
    name: "Windflower",
    description: "Delicate cup-shaped flowers in white, pink, or blue.",
    characteristics: "Perennial, thrives in cool, shaded areas",
    healthTip: "Leaves should be firm and flowers upright; wilted blooms indicate heat stress or water imbalance.",
    funFact: "Also known as Anemone, often blooms in early spring.",
  },
  {
    id: "japanese anemone",
    name: "Japanese Anemone",
    description: "Graceful pink or white flowers on tall stems.",
    characteristics: "Perennial, blooms late summer to fall",
    healthTip: "Healthy plants have upright stems and vibrant petals; drooping leaves or faded blooms suggest drought or insufficient nutrients.",
    funFact: "Commonly planted in woodland gardens.",
  },
  {
    id: "giant white arum lily",
    name: "Giant White Arum Lily",
    description: "Large white trumpet-shaped flowers.",
    characteristics: "Perennial, prefers moist, fertile soil",
    healthTip: "Firm leaves and pristine flowers indicate health; yellowing leaves may suggest nutrient deficiency or water stress.",
    funFact: "Symbolizes purity and rebirth.",
  },
  {
    id: "great masterwort",
    name: "Great Masterwort",
    description: "Clusters of small white or pale flowers.",
    characteristics: "Perennial, thrives in sun or partial shade",
    healthTip: "Healthy clusters are upright with green foliage; wilted or sparse blooms indicate drought or poor soil.",
    funFact: "Used historically as an herbal remedy.",
  },
  {
    id: "sweet pea",
    name: "Sweet Pea",
    description: "Climbing vines with fragrant colorful flowers.",
    characteristics: "Annual, needs support to climb",
    healthTip: "Upright, vibrant blooms indicate good growth; drooping stems or faded petals suggest lack of water or sunlight.",
    funFact: "Symbolizes delicate pleasure in flower language.",
  },
  {
    id: "tree mallow",
    name: "Tree Mallow",
    description: "Pink to purple flowers resembling hibiscus.",
    characteristics: "Shrub, blooms in summer",
    healthTip: "Healthy foliage and vibrant blooms show good growth; yellowing leaves suggest overwatering or nutrient issues.",
    funFact: "Attracts bees and butterflies.",
  },
  {
    id: "trumpet creeper",
    name: "Trumpet Creeper",
    description: "Orange-red trumpet-shaped flowers on climbing vines.",
    characteristics: "Fast-growing, attracts hummingbirds",
    healthTip: "Check that flowers are upright and vivid; drooping blooms indicate water stress or poor support.",
    funFact: "Also known as Campsis, used in gardens for vertical coverage.",
  },
  {
    id: "daffodil",
    name: "Daffodil",
    description: "Bright yellow trumpet-shaped flowers.",
    characteristics: "Bulbous perennial, blooms in spring",
    healthTip: "Firm, upright flowers indicate health; drooping stems suggest insufficient water or crowded bulbs.",
    funFact: "Symbol of renewal and spring.",
  },
  {
    id: "pincushion flower",
    name: "Pincushion Flower",
    description: "Round, spiky flowers with vibrant colors.",
    characteristics: "Perennial, drought-tolerant",
    healthTip: "Upright, bright blooms indicate good health; faded or bent flowers suggest water stress or insufficient sunlight.",
    funFact: "Attracts butterflies and bees.",
  },
  {
    id: "hard leaved pocket orchid",
    name: "Hard-Leaved Pocket Orchid",
    description: "Exotic orchid with tough leaves and delicate flowers.",
    characteristics: "Epiphytic perennial, prefers humidity",
    healthTip: "Firm leaves and vibrant blooms indicate health; shriveled flowers may mean insufficient humidity.",
    funFact: "Native to Australia and Asia.",
  },
  {
    id: "osteospermum",
    name: "Osteospermum",
    description: "Daisy-like flowers in vibrant colors.",
    characteristics: "Annual or perennial, heat-tolerant",
    healthTip: "Healthy blooms are open and upright; drooping flowers indicate heat stress or water imbalance.",
    funFact: "Also called African Daisy, popular in borders.",
  },
  {
    id: "tree poppy",
    name: "Tree Poppy",
    description: "Tall shrub with large, vibrant flowers.",
    characteristics: "Perennial, prefers sunny locations",
    healthTip: "Strong, upright stems and bright petals indicate health; wilting suggests drought or root problems.",
    funFact: "Native to Asia, used ornamentally.",
  },
  {
    id: "desert rose",
    name: "Desert Rose",
    description: "Succulent shrub with striking pink flowers.",
    characteristics: "Drought-tolerant, thrives in well-drained soil",
    healthTip: "Firm leaves and vibrant blooms indicate health; soft stems suggest overwatering.",
    funFact: "Also called Adenium, popular as a bonsai plant.",
  },
  {
    id: "bromelia",
    name: "Bromelia",
    description: "Tropical plant with colorful central flowers.",
    characteristics: "Evergreen, prefers humidity",
    healthTip: "Leaves should be firm and cup filled with water; brown tips indicate dehydration or low humidity.",
    funFact: "Often used as indoor ornamental plant.",
  },
  {
    id: "magnolia",
    name: "Magnolia",
    description: "Large, fragrant flowers, white or pink.",
    characteristics: "Shrub or small tree, blooms in spring",
    healthTip: "Vibrant flowers and dark green leaves indicate health; yellowing leaves may indicate poor soil or water stress.",
    funFact: "Symbolizes dignity and perseverance.",
  },
  {
    id: "english marigold",
    name: "English Marigold",
    description: "Bright yellow or orange flowers, aromatic foliage.",
    characteristics: "Annual, pest-repellent",
    healthTip: "Healthy blooms are bright; wilting or drooping leaves suggest drought.",
    funFact: "Used in companion planting to repel insects.",
  },
  {
    id: "bee balm",
    name: "Bee Balm",
    description: "Red, pink, or purple tubular flowers.",
    characteristics: "Perennial, attracts pollinators",
    healthTip: "Firm leaves and vibrant flowers indicate health; powdery mildew on leaves suggests high humidity or poor airflow.",
    funFact: "Popular with hummingbirds and bees.",
  },
  {
    id: "stemless gentian",
    name: "Stemless Gentian",
    description: "Deep blue, cup-shaped flowers close to the ground.",
    characteristics: "Perennial, alpine plant",
    healthTip: "Healthy blooms are vibrant; yellowing leaves indicate water or nutrient stress.",
    funFact: "Blooms late summer, often in meadows.",
  },
  {
    id: "mallow",
    name: "Mallow",
    description: "Pink to purple flowers, often with veined petals.",
    characteristics: "Perennial or annual, sun-loving",
    healthTip: "Vibrant flowers and upright stems indicate health; wilted leaves suggest drought stress.",
    funFact: "Used historically for herbal remedies.",
  },
  {
    id: "gaura",
    name: "Gaura",
    description: "Delicate white or pink flowers on thin stems.",
    characteristics: "Perennial, drought-tolerant",
    healthTip: "Upright, abundant blooms indicate health; drooping stems suggest water deficiency or heat stress.",
    funFact: "Sometimes called Wand Flower due to its thin stems.",
  },
  {
    id: "orange dahlia",
    name: "Orange Dahlia",
    description: "Large orange blooms with layered petals.",
    characteristics: "Perennial tuber, blooms summer to autumn",
    healthTip: "Healthy plants have strong stems and vibrant petals; drooping flowers suggest lack of water or nutrients.",
    funFact: "Popular in cut flower arrangements.",
  },
  {
    id: "pelargonium",
    name: "Pelargonium",
    description: "Clustered bright flowers with aromatic leaves.",
    characteristics: "Perennial, thrives in containers",
    healthTip: "Upright growth and fragrant leaves indicate health; yellowing leaves suggest overwatering.",
    funFact: "Often called geraniums in gardening.",
  },
  {
    id: "ruby lipped cattleya",
    name: "Ruby-Lipped Cattleya",
    description: "Orchid with vibrant pink lips and delicate petals.",
    characteristics: "Epiphytic orchid, humid environment",
    healthTip: "Firm leaves and vibrant flowers indicate health; shriveled blooms suggest low humidity.",
    funFact: "Highly prized in orchid collections.",
  },
  {
    id: "hippeastrum",
    name: "Hippeastrum",
    description: "Large trumpet-shaped flowers, usually red or white.",
    characteristics: "Bulbous perennial, blooms indoors or outdoors",
    healthTip: "Firm, upright leaves and vibrant flowers indicate health; drooping petals suggest insufficient light or water.",
    funFact: "Often sold as holiday bulbs indoors.",
  },
  {
    id: "artichoke",
    name: "Artichoke",
    description: "Large thistle-like flower buds, edible.",
    characteristics: "Perennial, grows tall, requires full sun",
    healthTip: "Healthy buds are firm; soft or discolored buds indicate stress or poor soil.",
    funFact: "Cultivated for its edible flower buds.",
  },
  {
    id: "gazania",
    name: "Gazania",
    description: "Bright daisy-like flowers in bold colors.",
    characteristics: "Low-growing, sun-loving perennial",
    healthTip: "Flowers open fully in sunlight indicate health; drooping blooms suggest insufficient light or water.",
    funFact: "Often used in rock gardens or borders.",
  },
  {
    id: "peruvian lily",
    name: "Peruvian Lily",
    description: "Tubular, often spotted flowers in multiple colors.",
    characteristics: "Bulbous perennial, blooms in summer",
    healthTip: "Healthy leaves and upright blooms indicate good health; fading flowers may need more water or sunlight.",
    funFact: "Also called Alstroemeria, popular in bouquets.",
  },
  {
    id: "mexican petunia",
    name: "Mexican Petunia",
    description: "Tall stems with purple or pink trumpet-shaped flowers.",
    characteristics: "Perennial, hardy, blooms summer to fall",
    healthTip: "Vibrant blooms and upright stems indicate health; drooping flowers may need more water or sunlight.",
    funFact: "Can naturalize easily in gardens.",
  },
  {
    id: "bird of paradise",
    name: "Bird of Paradise",
    description: "Exotic orange and blue flowers resembling a bird.",
    characteristics: "Tropical perennial, large leaves",
    healthTip: "Firm leaves and vibrant flowers indicate health; yellowing leaves suggest overwatering or nutrient deficiency.",
    funFact: "Symbol of paradise and freedom.",
  },
  {
    id: "sweet william",
    name: "Sweet William",
    description: "Clusters of small colorful flowers, fragrant.",
    characteristics: "Biennial, sun-loving",
    healthTip: "Healthy blooms are vibrant; faded flowers should be deadheaded to encourage more blooms.",
    funFact: "Popular in traditional English gardens.",
  },
  {
    id: "purple coneflower",
    name: "Purple Coneflower",
    description: "Purple petals surrounding a spiky central cone.",
    characteristics: "Perennial, attracts pollinators",
    healthTip: "Upright stems and vibrant cones indicate health; drooping flowers suggest drought stress.",
    funFact: "Used in herbal remedies for immune support.",
  },
  {
    id: "wild pansy",
    name: "Wild Pansy",
    description: "Small, delicate flowers in mixed colors.",
    characteristics: "Perennial, grows in meadows and gardens",
    healthTip: "Bright petals and upright growth indicate health; faded blooms may require deadheading.",
    funFact: "Edible flowers, used in salads and decorations.",
  },
  {
    id: "columbine",
    name: "Columbine",
    description: "Unique spurred flowers in various colors.",
    characteristics: "Perennial, attracts hummingbirds",
    healthTip: "Firm leaves and bright spurs indicate health; wilting flowers suggest insufficient water.",
    funFact: "Often symbolizes wisdom and strength.",
  },
  {
    id: "colts foot",
    name: "Colt's Foot",
    description: "Bright yellow flowers that appear early in spring.",
    characteristics: "Perennial, low-growing, spreads quickly",
    healthTip: "Vibrant flowers and upright leaves indicate health; wilted leaves may suggest too dry soil.",
    funFact: "Historically used for cough remedies.",
  },
  {
    id: "snapdragon",
    name: "Snapdragon",
    description: "Colorful tubular flowers that 'snap' open when squeezed.",
    characteristics: "Annual or perennial, upright growth",
    healthTip: "Upright stems and vivid colors indicate health; drooping flowers may need more water or nutrients.",
    funFact: "Named for its jaw-like flower shape.",
  },
  {
    id: "camellia",
    name: "Camellia",
    description: "Evergreen shrub with large, rose-like flowers.",
    characteristics: "Partial shade, acidic soil",
    healthTip: "Glossy leaves and vibrant blooms indicate health; yellowing leaves suggest improper soil pH or watering.",
    funFact: "Symbol of love and admiration.",
  },
  {
    id: "fritillary",
    name: "Fritillary",
    description: "Bell-shaped purple or checkered flowers.",
    characteristics: "Perennial bulb, prefers sun or partial shade",
    healthTip: "Firm leaves and upright flowers indicate health; faded blooms may need deadheading.",
    funFact: "Often found in woodland meadows.",
  },
  {
    id: "common dandelion",
    name: "Common Dandelion",
    description: "Bright yellow flowers, edible leaves and roots.",
    characteristics: "Perennial, resilient",
    healthTip: "Strong, upright stems and bright yellow flowers indicate health; drooping leaves may need more water.",
    funFact: "Used in salads and herbal teas.",
  },
  {
    id: "poinsettia",
    name: "Poinsettia",
    description: "Red and green foliage, commonly used during holidays.",
    characteristics: "Shrub, tropical, indoor plant",
    healthTip: "Vibrant red leaves indicate health; yellowing or dropping leaves suggest improper light or watering.",
    funFact: "Symbol of Christmas worldwide.",
  },
  {
    id: "primula",
    name: "Primula",
    description: "Clustered spring flowers in bright colors.",
    characteristics: "Perennial, prefers partial shade",
    healthTip: "Vibrant blooms and firm leaves indicate health; drooping flowers may need more water.",
    funFact: "Symbolizes youth and renewal.",
  },
  {
    id: "azalea",
    name: "Azalea",
    description: "Showy clusters of flowers in pink, red, or white.",
    characteristics: "Shrub, acid soil loving",
    healthTip: "Bright blooms and dark green leaves indicate health; wilting flowers may need more humidity or water.",
    funFact: "Popular in Asian gardens.",
  },
  {
    id: "californian poppy",
    name: "Californian Poppy",
    description: "Bright orange cup-shaped flowers.",
    characteristics: "Annual or perennial, drought-tolerant",
    healthTip: "Strong stems and vibrant petals indicate health; drooping flowers suggest dehydration.",
    funFact: "State flower of California.",
  },
  {
    id: "anthurium",
    name: "Anthurium",
    description: "Glossy, heart-shaped flowers, often red.",
    characteristics: "Tropical perennial, indoor plant",
    healthTip: "Shiny leaves and upright spathes indicate health; yellowing leaves may need less direct sunlight or more humidity.",
    funFact: "Also called Flamingo Flower.",
  },
  {
    id: "clematis",
    name: "Clematis",
    description: "Climbing vine with large, colorful flowers.",
    characteristics: "Perennial, requires support",
    healthTip: "Firm leaves and vibrant flowers indicate health; weak stems may need more support or nutrients.",
    funFact: "Popular for garden trellises and arbors.",
  },
  {
    id: "geranium",
    name: "Geranium",
    description: "Bright flowers, often pink or red, aromatic leaves.",
    characteristics: "Perennial, sun-loving",
    healthTip: "Vivid blooms and firm leaves indicate health; yellowing leaves may indicate overwatering or nutrient deficiency.",
    funFact: "Popular in containers and window boxes.",
  },
  {
    id: "thorn apple",
    name: "Thorn Apple",
    description: "Spiky seed pods with fragrant flowers.",
    characteristics: "Perennial, toxic if ingested",
    healthTip: "Upright growth and strong stems indicate health; avoid ingestion and wear gloves when handling.",
    funFact: "Also called Datura; used historically in medicine.",
  },
  {
    id: "barbeton daisy",
    name: "Barbeton Daisy",
    description: "Vibrant daisy-like flowers in pink and yellow.",
    characteristics: "Perennial, drought-tolerant",
    healthTip: "Bright blooms and upright stems indicate health; drooping flowers may need more water.",
    funFact: "Native to South Africa.",
  },
  {
    id: "bougainvillea",
    name: "Bougainvillea",
    description: "Colorful bracts surrounding tiny white flowers.",
    characteristics: "Climbing vine, drought-tolerant",
    healthTip: "Vivid bracts and firm leaves indicate good health; pale or drooping leaves suggest insufficient sunlight or water.",
    funFact: "Popular in tropical and subtropical gardens.",
  },
  {
    id: "sword lily",
    name: "Sword Lily",
    description: "Tall stems with trumpet-shaped flowers.",
    characteristics: "Perennial, prefers sunny locations",
    healthTip: "Upright stems and vibrant flowers indicate health; weak stems may need staking or more sunlight.",
    funFact: "Also known as Gladiolus.",
  },
  {
    id: "lotus",
    name: "Lotus",
    description: "Aquatic flower with broad petals and a central seed pod.",
    characteristics: "Grows in ponds or shallow water",
    healthTip: "Full, open blooms and healthy leaves indicate health; wilting leaves may need more sunlight or warmer water.",
    funFact: "Symbol of purity and enlightenment in many cultures.",
  },
  {
    id: "cyclamen",
    name: "Cyclamen",
    description: "Heart-shaped leaves and delicate upswept flowers.",
    characteristics: "Perennial, prefers shade and cool conditions",
    healthTip: "Firm leaves and upright flowers indicate health; drooping foliage suggests excessive heat or water stress.",
    funFact: "Blooms in autumn and winter indoors.",
  },
  {
    id: "frangipani",
    name: "Frangipani",
    description: "Fragrant tropical flowers, often white or pink.",
    characteristics: "Small tree or shrub, thrives in warm climates",
    healthTip: "Bright blooms and firm leaves indicate health; leaf yellowing may indicate nutrient deficiency or overwatering.",
    funFact: "Flowers often used in leis and perfumes.",
  },
  {
    id: "watercress",
    name: "Watercress",
    description: "Aquatic plant with small green leaves and white flowers.",
    characteristics: "Fast-growing, grows in shallow water",
    healthTip: "Healthy watercress has crisp, dark green leaves; wilted leaves suggest insufficient water flow or nutrients.",
    funFact: "Edible, high in vitamins, often used in salads.",
  },
  {
    id: "water lily",
    name: "Water Lily",
    description: "Floating aquatic flower with broad leaves and showy blooms.",
    characteristics: "Requires pond or water garden",
    healthTip: "Open flowers and healthy floating leaves indicate health; yellowing leaves may need better water quality.",
    funFact: "Flowers open in the morning and close at night.",
  },
  {
    id: "wallflower",
    name: "Wallflower",
    description: "Clusters of fragrant flowers in bright colors.",
    characteristics: "Perennial, tolerates poor soil",
    healthTip: "Vibrant blooms and healthy leaves indicate good growth; wilting or discolored foliage may need better soil drainage or sunlight.",
    funFact: "Used traditionally in cottage gardens.",
  },
  {
    id: "passion flower",
    name: "Passion Flower",
    description: "Exotic, intricate flowers with vibrant colors.",
    characteristics: "Climbing vine, tropical",
    healthTip: "Healthy vines have lush leaves and fully open flowers; yellowing leaves may indicate nutrient deficiency or insufficient sunlight.",
    funFact: "Symbolic in Christian art; attracts pollinators.",
  },
  {
    id: "petunia",
    name: "Petunia",
    description: "Brightly colored, trumpet-shaped flowers.",
    characteristics: "Annual, bushy growth",
    healthTip: "Healthy petunias have abundant flowers and deep green leaves; fading blooms may require deadheading and more sunlight.",
    funFact: "Popular in hanging baskets and garden beds.",
  }
];

// 🌿 Plants
const plantData = [
  {
    id: "bamboo (giant bamboo)",
    name: "Bamboo",
    description: "A versatile fast-growing grass species that resembles a woody tree and is widely used in Asian landscaping, construction, and culture.",
    characteristics: "Tall, hollow, jointed stems that can grow several centimeters per day. Evergreen foliage and grows in tight clumping or running forms depending on species.",
    healthTip: "Thrives in moist but well-drained soil with partial to full sunlight. Requires controlled space due to aggressive spreading in certain species.",
    funFact: "Some species of bamboo can grow up to 90 cm in a single day — making it one of the fastest-growing plants on Earth."
  },
  {
    id: "heliconia (lobster claw)",
    name: "Heliconia",
    description: "A vibrant tropical flowering plant known for its bold, colorful bracts resembling lobster claws or bird beaks.",
    characteristics: "Grows in clumps with large banana-like leaves and produces bright red, orange, or yellow bracts that attract pollinators like hummingbirds.",
    healthTip: "Requires warm, humid conditions, regular watering, and partial shade. Ideal for tropical gardens and attracts beneficial wildlife.",
    funFact: "Commonly called 'Lobster Claw' or 'False Bird of Paradise' due to its resemblance to the Bird of Paradise flower."
  },
  {
    id: "monstera (swiss cheese plant)",
    name: "Monstera",
    description: "A popular tropical climbing plant recognized for its large, glossy leaves with natural holes or splits, often used as indoor décor.",
    characteristics: "Epiphytic plant that grows by climbing trees with aerial roots. Leaves develop fenestrations as the plant matures.",
    healthTip: "Prefers bright, indirect light and high humidity. Overwatering can cause root rot, so drainage is essential in cultivation.",
    funFact: "Monstera leaves were traditionally believed in some cultures to attract prosperity and positive energy into homes."
  },
  {
    id: "philodendron",
    name: "Philodendron",
    description: "A tropical climbing plant popular for its large, glossy leaves and ease of indoor cultivation.",
    characteristics: "Evergreen, often grows as a vine or shrub, with heart-shaped leaves that vary by species.",
    healthTip: "Thrives in indirect sunlight and well-drained soil. Avoid overwatering; leaves may yellow if roots are waterlogged.",
    funFact: "Philodendron is derived from Greek words meaning 'love tree', reflecting its heart-shaped leaves."
  },
  {
    id: "rain tree",
    name: "Rain Tree",
    description: "A large tropical tree famous for its expansive canopy that provides shade and its sensitive leaf movements in response to sunlight.",
    characteristics: "Broad-spreading branches, compound leaves that fold in the evening or when touched, and flat-topped canopy.",
    healthTip: "Requires full sun and rich, well-drained soil. Regular pruning may be needed to prevent excessive shade or root crowding.",
    funFact: "Also known as Samanea saman, its leaves mimic rainfall behavior, hence the name 'Rain Tree'."
  },
  {
    id: "travelers palm",
    name: "Travelers Palm",
    description: "A striking tropical plant with fan-shaped leaves resembling a hand-held palm, native to Madagascar.",
    characteristics: "Produces large paddle-shaped leaves and occasionally fragrant flowers. Can reach 10–15 meters in height.",
    healthTip: "Requires full sun and regular watering. Protect from frost and strong winds.",
    funFact: "Leaves of this plant can collect rainwater at the base, historically used by travelers as a water source."
  },
  {
    id: "caladium (angel wings)",
    name: "Caladium",
    description: "A tropical ornamental plant known for its heart-shaped colorful leaves rather than flowers.",
    characteristics: "Low-growing, produces red, pink, green, and white variegated foliage. Grows from tubers.",
    healthTip: "Prefers partial shade and moist, well-drained soil. Avoid direct sunlight to prevent leaf burn.",
    funFact: "Caladium is often referred to as 'Elephant Ear' due to its large leaf size."
  },
  {
    id: "pandan plant",
    name: "Pandan Plant",
    description: "A tropical plant valued for its fragrant leaves widely used in Southeast Asian cooking.",
    characteristics: "Clumping grass-like plant with long, slender, spiky leaves. Can grow in soil or pots.",
    healthTip: "Requires full sun to partial shade and moist soil. Regular trimming encourages new growth.",
    funFact: "Pandan leaves are used to flavor rice, desserts, and beverages and are sometimes woven into mats or crafts."
  },
  {
    id: "coconut palm",
    name: "Coconut Palm",
    description: "A quintessential tropical palm known for its edible coconuts and tall, slender trunk.",
    characteristics: "Evergreen, can reach heights of 30 meters, produces clusters of coconuts and feathery fronds.",
    healthTip: "Thrives in sandy, well-drained soil and full sun. Watering is crucial during establishment.",
    funFact: "Coconut palms are often called 'The Tree of Life' because every part of the tree can be used for food, shelter, or tools."
  },
  {
    id: "areca palm",
    name: "Areca Palm",
    description: "A popular ornamental palm commonly used indoors or in gardens for its feathery fronds.",
    characteristics: "Slender trunk, pinnate leaves, grows in clumps or single stems. Can tolerate partial shade.",
    healthTip: "Prefers bright indirect light and moist, well-drained soil. Avoid overwatering to prevent root rot.",
    funFact: "Areca palms are believed to purify air and are widely used in tropical landscaping."
  }
];

// 🏛️ Architecture
const architectureData = [
  {
    id: "bandstand",
    name: "Bandstand",
    description: "A raised, open-air structure typically used for musical performances in parks and gardens.",
    characteristics: "Circular or octagonal design, often with a decorative roof and railings, providing shelter for performers.",
    funFact: "Bandstands became popular in the 19th century as social gathering spots for community concerts and events."
  },
  {
    id: "botany centre",
    name: "Botany Centre",
    description: "An educational facility within a botanical garden focused on plant research, conservation, and public education.",
    characteristics: "Indoor space with laboratories, exhibition halls, and interactive displays for visitors of all ages.",
    funFact: "Botany centres often host workshops, plant identification courses, and citizen science programs."
  },
  {
    id: "centre for ethnobotany",
    name: "Centre for Ethnobotany",
    description: "A specialized research and exhibition centre dedicated to the study of how humans use and interact with plants.",
    characteristics: "Displays traditional medicines, cultural artifacts, and plants of ethnobotanical significance. Combines education with scientific research.",
    funFact: "Ethnobotany combines anthropology and botany, exploring the cultural and medicinal significance of plants."
  },
  {
    id: "heritage museum",
    name: "Heritage Museum",
    description: "A museum showcasing the historical, cultural, and botanical heritage of a region, often within a botanical garden or park.",
    characteristics: "Indoor exhibition spaces with artifacts, models, photographs, and archival collections highlighting local history and horticulture.",
    funFact: "Many heritage museums within gardens also document the evolution of garden design and plant collections over time."
  },
  {
    id: "shaw foundation symphony stage",
    name: "Shaw Foundation Symphony Stage",
    description: "A large outdoor performance venue designed for symphonies, concerts, and cultural events.",
    characteristics: "Open-air amphitheatre with tiered seating, elevated stage, and acoustic design to project sound to large audiences.",
    funFact: "Named after philanthropist Shaw Foundation, it is a hub for cultural performances and community gatherings in botanical gardens."
  },
  {
  id: "forest discovery centre",
  name: "Forest Discovery Centre",
  description: "An immersive educational hub within the Singapore Botanic Gardens dedicated to rainforest conservation and biodiversity awareness.",
  characteristics: "Features interactive exhibits, informative displays, and elevated walkways surrounded by lush canopy trees showcasing native forest ecosystems.",
  funFact: "The centre highlights Singapore’s reforestation efforts and offers a bird’s-eye view of the surrounding treetops from the OCBC Arboretum."
  }
];

async function populateObjectInfo() {
  try {
    console.log("🌿 Starting Firestore population...");

    const allObjects = [...flowerData, ...plantData, ...architectureData];

    for (const obj of allObjects) {
      const docRef = db.doc(`objectInfo/${obj.id}`);
      const docSnap = await docRef.get();
      if (!docSnap.exists) {
        await docRef.set({ ...obj, createdAt: new Date() });
        console.log(`✅ Added object: ${obj.name}`);
      } else {
        console.log(`⚠️ Skipped existing object: ${obj.name}`);
      }
    }

    console.log("🎉 All object data populated successfully!");
  } catch (error) {
    console.error("❌ Error populating Firestore:", error);
  }
}

populateObjectInfo();